Description of plus_
plus_
PURPOSE
Adds two SF_Efield
SYNOPSIS
function [a] = plus_(a,b)
DESCRIPTION
Adds two SF_Efield
CROSS-REFERENCE INFORMATION
This function calls:
plus_ Adds two SF_Efield
This function is called by:
SF_Efield
plus_ Adds two SF_Efield
SOURCE CODE
function [a] = plus_(a,b)
%Adds two SF_Efield
    if ~isa(a, 'Yggdrasil.SF_Efield') || ~isa(b, 'Yggdrasil.SF_Efield')
        error('Can single frequency Efields only add with itself.')
    end
    % If they are orthogonal time wise
    if a.frequency ~= b.frequency || a.arrangement ~= b.arrangement
        mf_obj = Yggdrasil.MF_Efield();
        t = mf_obj + a;
        a = (t + b);
        return;
    end
    a = plus_@Yggdrasil.Octree(a,b);
    a.C = a.C + b.C;
end