Description of SF_Efield
SF_Efield
PURPOSE
SYNOPSIS
This is a script file.
DESCRIPTION
CROSS-REFERENCE INFORMATION
This function calls:
SF_Efield
disp [ output ] = DISP(sf_e) The disp for single frequincy E-field.
fetch_content varargout = FETCH_CONTENT(obj, field1, field2 ...)
get_adr adr = GET_ADR(self, adr)
get_data data = GET_DATA(self, data)
get_meta meta = GET_META(self, meta)
mtimes_ [a] = MTIMES_(a, b)
plus_ Adds two SF_Efield
scalar_prod_ oct = SCALAR_PROD(a, b)
scalar_prod_integral_ oct = SCALAR_PROD(a, b)
set_adr adr = SET_ADR(self, adr)
set_data data = SET_DATA(self, data)
set_meta meta = SET_META(self, meta)
store_content STORE_CONTENT(self)
times_ [a] = MTIMES_(a, b)
uminus [self] = UMINUS(self)
This function is called by:
SF_Efield
SUBFUNCTIONS
function self = SF_Efield(frequency, antenna_id, arrangement)
function output = hash(self)
function output = priority()
SOURCE CODE
classdef SF_Efield < Yggdrasil.Octree
    properties
        frequency;
        arrangement;
        C;
        is_content_local = true;
    end
    properties (Access = protected)
        my_hash;
    end
    methods
        function self = SF_Efield(frequency, antenna_id, arrangement)
            if nargin < 2
                error('Too few input arguments.');
            end
            if nargin > 3
                error('Too many input arguments.');
            end
            % Initialise temporary placeholder octree
            self@Yggdrasil.Octree(NaN);
            self.is_content_local = false; % Use remote content
            % Set up internal SF_Efield properties
            self.frequency = frequency;
            if nargin == 2
                self.arrangement = 1;
            else
                self.arrangement = arrangement;
            end
            % Set up antenna properties
            self.C = Yggdrasil.YggMap();
            self.C = self.C + {antenna_id, 1};
            % Set up hash
            self.my_hash = {['A' num2str(self.arrangement) ...
                            'F' num2str(self.frequency)]};
        end
        self = store_content(self);
        varargout = fetch_content(obj, varargin);
        function output = hash(self)
            output = self.my_hash;
        end
        output = disp(sf_e);
        self   = uminus(self);
    end
    methods (Access = protected)
        [self, data] = set_data(self, data);
        [self, adr ] = set_adr(self, adr);
        [self, meta] = set_meta(self, meta);
        data = get_data(self, data);
        adr = get_adr(self, adr);
        meta = get_meta(self, meta);
    end
    methods (Static)
        function output = priority()
           output = priority@Yggdrasil.Octree() + 1;
        end
        output = plus_(a,b);
        output = mtimes_(a,b);
        output = times_(a,b);
        output = scalar_prod_(a,b);
        output = scalar_prod_integral_(a,b);
     end
 end