Description of MF_Efield
MF_Efield
PURPOSE
SYNOPSIS
This is a script file.
DESCRIPTION
CROSS-REFERENCE INFORMATION
This function calls:
MF_Efield
abs_sq [ oct ] = ABS_SQ(mf_obj)
input_chk [x,y,mf_num] = INPUT_CHK(a,b)
mtimes_ output = MTIMES_(a,b)
plus_ a = plus_(a,b)
scalar_prod_ S = SCALAR_PROD_(a,b)
scalar_prod_integral_ S = SCALAR_PROD_INTEGRAL_(a,b)
uminus a = UMINUS(a)
weight_ a = WEIGHT_(a,w)
This function is called by:
MF_Efield
SUBFUNCTIONS
function self = MF_Efield()
function disp(sf_e)
function output = priority()
SOURCE CODE
classdef MF_Efield < Yggdrasil.AbstractOctreePriority
    properties
        E = Yggdrasil.YggMap();
    end
    methods
        function self = MF_Efield()
        end
        function disp(sf_e)
            % TBW
            disp('Hi, I''m an MF_Efield.');
        end
        self   = uminus(self)
        output = abs_sq(self)
    end
    methods (Static, Access = private)
         [x,y,mf_num] = input_chk(a,b)
    end
    methods (Static)
        function output = priority()
           output = Yggdrasil.SF_Efield.priority() + 1;
        end
        a = plus_(a,b)
        a = mtimes_(a,b)
        S = scalar_prod_(a,b)
        S = scalar_prod_integral_(a,b)
        a = weight_(a,w)
     end
 end