Description of abs_sq
abs_sq
PURPOSE
self = ABS_SQ(self)
SYNOPSIS
function [ self ] = abs_sq(self)
DESCRIPTION
self = ABS_SQ(self)
  A function that can handle both matrices and octrees.
  It calculates the vectorial sum(abs(...)^2,4) operation.
CROSS-REFERENCE INFORMATION
This function calls:
imag [oct] = IMAG(oct)
real [oct] = REAL(oct)
sum [ oct ] = SUM(oct, const)
This function is called by:
Octree The great octree class
SOURCE CODE
function [ self ] = abs_sq(self)
%self = ABS_SQ(self)
%  A function that can handle both matrices and octrees.
%  It calculates the vectorial sum(abs(...)^2,4) operation.
    self.data = sum(real(self.data).^2,1) + sum(imag(self.data).^2,1);
    self.meta.eps = 2*self.meta.eps;
end