Description of all
all
PURPOSE
output = ALL(oct)
SYNOPSIS
function output = all(oct)
DESCRIPTION
output = ALL(oct)
  Implements all for octrees
CROSS-REFERENCE INFORMATION
This function calls:
all output = ALL(oct)
This function is called by:
Octree The great octree class
all output = ALL(oct)
SOURCE CODE
function output = all(oct)
%output = ALL(oct)
%  Implements all for octrees
    output = all(oct.data(:) ~= 0);
end