Description of any
any
PURPOSE
output = ANY(oct)
SYNOPSIS
function output = any(oct)
DESCRIPTION
output = ANY(oct)
  Returns 1 if there is one or more non-zero elements in the octrees data
CROSS-REFERENCE INFORMATION
This function calls:
any output = ANY(oct)
This function is called by:
Octree The great octree class
any output = ANY(oct)
SOURCE CODE
function output = any(oct)
%output = ANY(oct)
%  Returns 1 if there is one or more non-zero elements in the octrees data
    output = any(oct.data(:) ~= 0);
end