Description of imag
imag
PURPOSE
[oct] = IMAG(oct)
SYNOPSIS
function [oct] = imag(oct)
DESCRIPTION
[oct] = IMAG(oct)
  Extracts the imaginary part of the data
CROSS-REFERENCE INFORMATION
This function calls:
imag [oct] = IMAG(oct)
This function is called by:
Octree The great octree class
abs_sq self = ABS_SQ(self)
disp DISP(oct)
imag [oct] = IMAG(oct)
SOURCE CODE
function [oct] = imag(oct)
%[oct] = IMAG(oct)
%  Extracts the imaginary part of the data
    oct.data = imag(oct.data);
end