Description of integral
integral
PURPOSE
output = INTEGRAL(a, w)
SYNOPSIS
function output = integral(a, w)
DESCRIPTION
output = INTEGRAL(a, w)
  Integrates over all elements in an octree with an optional weight
CROSS-REFERENCE INFORMATION
This function calls:
size [ varargout ] = SIZE(oct, dim)
zeros [ oct ] = ZEROS(mat_size, (OPTIONAL) eps)
This function is called by:
Octree The great octree class
SOURCE CODE
function output = integral(a, w)
%output = INTEGRAL(a, w)
%  Integrates over all elements in an octree with an optional weight
    narginchk(1,2);
    if nargin == 2
        a=a.weight(w);
    end
    output = zeros(1, size(a,4));
    for i = 1:length(output)
        output(i) = a.data(i,:)*single(diff(a.adr.'));
    end
end