Description of rand
rand
PURPOSE
[oct] = RAND(matsize, rel_eps)
SYNOPSIS
function [oct] = rand(matsize, rel_eps)
DESCRIPTION
[oct] = RAND(matsize, rel_eps)
  Creates a octree corresponding to a randomized matrix with size matsize
  and epsilon value eps.
CROSS-REFERENCE INFORMATION
This function calls:
rand [oct] = RAND(matsize, rel_eps)
This function is called by:
Octree The great octree class
rand [oct] = RAND(matsize, rel_eps)
SOURCE CODE
function [oct] = rand(matsize, rel_eps)
%[oct] = RAND(matsize, rel_eps)
%  Creates a octree corresponding to a randomized matrix with size matsize
%  and epsilon value eps.
    if exist('rel_eps', 'var')
        oct = Yggdrasil.Octree(rand(matsize), 'rel_eps', rel_eps);
    else
        oct = Yggdrasil.Octree(rand(matsize));
    end
end