Description of real
real
PURPOSE
[oct] = REAL(oct)
SYNOPSIS
function [oct] = real(oct)
DESCRIPTION
[oct] = REAL(oct)
  Extracts the real part of the data
CROSS-REFERENCE INFORMATION
This function calls:
real [oct] = REAL(oct)
This function is called by:
Octree The great octree class
abs_sq self = ABS_SQ(self)
disp DISP(oct)
real [oct] = REAL(oct)
SOURCE CODE
function [oct] = real(oct)
%[oct] = REAL(oct)
%  Extracts the real part of the data
    oct.data = real(oct.data);
end