Description of sum
sum
PURPOSE
[ oct ] = SUM(oct, const)
SYNOPSIS
function [ oct ] = sum(oct, const)
DESCRIPTION
[ oct ] = SUM(oct, const)
  This function is the octree equivalent to matrix summation along
  the fourth dimension. The function should be called as
  SUM(oct, 4), all other constants const are invalid.
CROSS-REFERENCE INFORMATION
This function calls:
sum [ oct ] = SUM(oct, const)
This function is called by:
Octree The great octree class
abs_sq self = ABS_SQ(self)
sum [ oct ] = SUM(oct, const)
SOURCE CODE
function [ oct ] = sum(oct, const)
%[ oct ] = SUM(oct, const)
%  This function is the octree equivalent to matrix summation along
%  the fourth dimension. The function should be called as
%  SUM(oct, 4), all other constants const are invalid.
    if nargin ~= 2
       error(['Invalid number of arguments. This function is equivalent ' ...
           'to matrix summation in the fourth dimension, and because of'...
           ' this needs to be called as "sum(oct, 4)".'])
    end
    if const ~= 4
       error(['Invalid input. This function is equivalent ' ...
           'to matrix summation in the fourth dimension, and because of'...
           ' this needs to be called as "sum(oct, 4)".'])
    end
    oct.data = sum(oct.data,1);
end