Description of conj
conj
PURPOSE
a = CONJ(a)
SYNOPSIS
function a = conj(a)
DESCRIPTION
a = CONJ(a)
   Conjugates the whole polynomial
CROSS-REFERENCE INFORMATION
This function calls:
conj a = CONJ(a)
This function is called by:
CPoly This class handles complex polynomials of the type
absSq a = ABSSQ(a)
conj a = CONJ(a)
evaluate val = EVALUATE(poly, z_vec)
SOURCE CODE
function a = conj(a)
%a = CONJ(a)
%   Conjugates the whole polynomial
    %Conjugates the monomials by flipping and changing sign
    for i = length(a.monom)
        a.monom{i} = -flipud(a.monom{i});
    end
    %And the coefficients can be conjugated by
    a.coefficients = conj(a.coefficients);
end