Description of CPoly
CPoly
PURPOSE
This class handles complex polynomials of the type
SYNOPSIS
This is a script file.
DESCRIPTION
This class handles complex polynomials of the type
2*c_1*conj(c_2) + 4.2i*c_1*c_2.
It is designed to speed up and to simplify creation of large polynomials.
CROSS-REFERENCE INFORMATION
This function calls:
CPoly This class handles complex polynomials of the type
conj a = CONJ(a)
eq equal = EQ(a,b)
evaluate val = EVALUATE(poly, z_vec)
isconst is_const = ISCONST(a)
minus a = MINUS(a,b)
mtimes a = MTIMES(a,b)
ne not_equal = NE(a,b)
plus a = PLUS(a,b)
reduce b = REDUCE(a)
uminus a = UMINUS(a)
unique_index index = UNIQUE_INDEX(monom)
uplus a = UPLUS(a)
This function is called by:
CPoly This class handles complex polynomials of the type
mtimes a = MTIMES(a,b)
reduce b = REDUCE(a)
SUBFUNCTIONS
function obj = CPoly(coefficient, variables)
SOURCE CODE
%This class handles complex polynomials of the type
%2*c_1*conj(c_2) + 4.2i*c_1*c_2.
%It is designed to speed up and to simplify creation of large polynomials.
classdef CPoly
   properties
      monom
      coefficients
   end
   methods
      %Constructor
      function obj = CPoly(coefficient, variables)
         if nargin == 0
            error('Too few input arguments');
         end
         if ~(nargin == 1 | nargin == 2)
            error('Too many input arguments');
         end
         if ~isnumeric(coefficient)
             error('Value must be numeric or defining a monomial.');
         end
         if nargin == 1
               obj.monom = {[]};
               obj.coefficients = coefficient;
         elseif nargin == 2
               if ~isnumeric(variables)
                    error('Variables must be given as a integer.');
               end
               if length(variables) ~= numel(variables)
                  error('The integer vector defining the monomial needs to be 1 dimensional.');
               end
               if length(variables) ~= size(variables,1)
                  error('The integer vector defining the monomial needs to be a column vector.');
               end
               if ~all(round(variables)==variables)
                  error('The vector defining the monomial needs to be an integer vector.');
               end
               if any(variables == 0)
                  error('The vector defining the monomial can not contain any zeroes.');
               end
               obj.monom = {sort(int64(variables),'ascend')};
               obj.coefficients = coefficient;
         end
      end
      output = plus(a,b);
      output = minus(a,b);
      output = uplus(a,b);
      output = uminus(a,b);
      output = mtimes(a,b);
      output = mpower(a,b);
      output = conj(a);
      output = reduce(a);
      output = eq(a,b);
      output = ne(a,b);
      output = isconst(a);
   end
   methods (Static)
       output = unique_index(cell_of_vectors);
   end
   methods
       output = evaluate(obj, vektor_of_z);
   end
end